language: java
jdk:
  - openjdk7

notifications:
  email: false

before_install:
  - ulimit -u 65535

script: ./gradlew --info --parallel -PtestForks=2 test itest -s

after_success:
  - ./gradlew jacocoReport coveralls
